<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 02.12.2014
 * Time: 18:47
 */

if(count($this->studios)) {
    echo '<table border="1">
        <tr>
            <th>Name </th>
            <th>Country </th>
            <th>City</th>
            <th>Address</th>
            <th>Postcode</th>
            <th>Contact person</th>
        </tr>';

    foreach ($this->studios as $studio) {

        echo "<td>" .$studio->name_studio. "</td>";
        echo "<td>" .$studio->country. "</td>";
        echo "<td>" .$studio->city. "</td>";
        echo "<td>" .$studio->address. "</td>";
        echo "<td>" .$studio->postcode . "</td>";
        echo "<td>" .$studio->contact_person . "</td>";
        echo "</tr>";

    }
    echo "</table>";
}else{
    echo "<p>List  films not found</p>";
}
